### ISSUE TITLE
Error: 3 INVALID_ARGUMENT: Invalid instances

### ISSUE THREAD

**Issue by herenickname** [googleapis/nodejs-ai-platform#342]
Code:
```ts
import axios from 'axios'
import * as AIPlatform from '@google-cloud/aiplatform'
const {
    instance: { ImageClassificationPredictionInstance },
    params: { ImageClassificationPredictionParams },
    prediction: { ClassificationPredictionResult }
} = AIPlatform.protos.google.cloud.aiplatform.v1.schema.predict
const { PredictionServiceClient } = AIPlatform.v1

export class VertexAi {
    private modelEndpoint = `projects/{project}/locations/us-central1/endpoints/{endpointid}`

    private predictionServiceClient = new PredictionServiceClient({
        apiEndpoint: 'us-central1-aiplatform.googleapis.com',
        keyFilename: 'gcloud.key'
    })

    async evaluate(imageUrl: string) {
        const imageBase64Content = await axios
            .get(imageUrl, { responseType: 'arraybuffer' })
            .then((response) => Buffer.from(response.data, 'binary').toString('base64'))

        const parameters = new ImageClassificationPredictionParams({
            confidenceThreshold: 0.7,
            maxPredictions: 5
        }).toJSON()

        const instance = new ImageClassificationPredictionInstance({
            content: imageBase64Content,
            mimeType: 'image/jpeg'
        }).toJSON()

        const [response] = await this.predictionServiceClient.predict({
            endpoint: this.modelEndpoint,
            instances: [instance],
            parameters
        })

        const [prediction] = response.predictions

        const predictionResultObj = ClassificationPredictionResult.fromObject(prediction)
        for (const [i, label] of predictionResultObj.displayNames.entries()) {
            console.log(`\tDisplay name: ${label}`)
            console.log(`\tConfidences: ${predictionResultObj.confidences[i]}`)
            console.log(`\tIDs: ${predictionResultObj.ids[i]}\n\n`)
        }

        return predictionResultObj
    }
}
```

Before using your library, I was trying to send the same image (with the same imageBase64Content) to the route `https://us-central1-aiplatform.googleapis.com/v1/projects/${PROJECT_ID}/locations/us-central1/endpoints/${ENDPOINT_ID}:predict` through axios.post.
I succeeded and got the expected correct answer.

Through the `@google-cloud/aiplatform` library I get the error:
```
/root/v3/node_modules/@grpc/grpc-js/build/src/call.js:31
    return Object.assign(new Error(message), status);
                         ^

Error: 3 INVALID_ARGUMENT: Invalid instances: 
    at Object.callErrorFromStatus (/root/v3/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/root/v3/node_modules/@grpc/grpc-js/build/src/client.js:189:52)
    at Object.onReceiveStatus (/root/v3/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
    at Object.onReceiveStatus (/root/v3/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /root/v3/node_modules/@grpc/grpc-js/build/src/call-stream.js:187:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 3,
  details: 'Invalid instances: ',
  metadata: Metadata {
    internalRepr: Map(1) {
      'grpc-server-stats-bin' => [
        Buffer(10) [Uint8Array] [
          0, 0, 255, 0, 228,
          2, 0,   0, 0,   0
        ]
      ]
    },
    options: {}
  }
}
```

Unfortunately, I can't find the problem myself. Where is the mistake?

**Comment by herenickname** [comment]
```ts
import { JWT } from 'google-auth-library'
...

export class VertexAi {
    ...
    async evaluate(imageUrl: string) {
        ....
        const servicekeybuffer = await readFile('your-service-account-credentials.json')
        const servicekey = JSON.parse(servicekeybuffer.toString())

        const client = new JWT({
            email: servicekey.client_email,
            key: servicekey.private_key,
            scopes: ['https://www.googleapis.com/auth/cloud-platform']
        })

        const { data } = await client.request<any>({
            url: `https://us-central1-aiplatform.googleapis.com/v1/` + this.modelEndpoint + ':predict',
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            data: {
                instances: [instance],
                parameters
            }
        })

        const [prediction] = data.predictions
        ...
```

Finally, a working example for interacting with the http api through the service account.
Suddenly it will be useful to someone.

**Comment by msrks** [comment]
same error occured for me

**Comment by telpirion** [comment]
@herenickname Thank you for posting your code here!

For future questions about the client library and samples hosted in this repo, please go to one of these repos:

+ [Samples](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/main/ai-platform/snippets)
+ [Library](https://github.com/googleapis/google-cloud-node/tree/main/packages)

**Comment by herenickname** [comment]
@telpirion unfortunately, the code I provided is a crutch for solving the problem directly through API requests, and not through the library
